### ISSUE TITLE
code block background bug

### ISSUE THREAD

**Issue by Richard-CokeCola** [nodejh/hugo-theme-mini#104]
Hi, first I just want to say thank you for your great work, I absolutely love this theme. However, there is a tiny bug in the code block. You know there is a grey colour background in the code block, it works fine when the code is short. If the code is very long when there is a progress bar, the background colour will just vanish at last. 
Best wishes!

**Comment by Richard-CokeCola** [comment]
I find out that this bug is alrady fixed in the latest vision. Sorry to bother. Thanks again!

**Comment by nodejh** [comment]
Yes, I have fixed this issue in the latest version :-)  

This is the same issue: https://github.com/nodejh/hugo-theme-mini/issues/90

**Comment by Richard-CokeCola** [comment]
Yeah, just tried it, the latest vision is great! Thank you very much.
