### ISSUE TITLE
Ordered lists not rendered correctly

### ISSUE THREAD

**Issue by ByteThis** [nodejh/hugo-theme-mini#21]
Cannot render an Ordered list with line breaks in between, or code snippets.

This:
```
1. One

2. Two

3. Three
```

Outputs this

```
1. 
One

2.
Two

3.
Three
```

My goal is to have some multi-line code inside each list item.
If I try to use this:
```
1. One<br><br>

/```
testing
some
code
/```

2. Two<br><br>
3. Three<br><br>
```

(added / on purpose so the code ticks are displayed)

I get

![screen shot 2017-08-17 at 18 44 25](https://user-images.githubusercontent.com/10193860/29425781-66cb6d2c-837c-11e7-972e-1809ca378db1.png)

Which contains wrong numeration.

**Comment by nielsen** [comment]
That looks like Markdown rendering as expected -- try indenting each line of the embedded snippet 4 spaces. Should keep the number consistent.
