### ISSUE TITLE
Some Issues & Queries

### ISSUE THREAD

**Issue by wasim-ullah** [nodejh/hugo-theme-mini#36]
1. Why do you think the tags terms are in small fonts? https://wasimu.com/tags/
As seen in: http://bit.ly/2kxSgXb
2. What is the function of next and previous if it's not showing up in posts?
3. What's author for, if it's not showing up?
4. What's menu for?
5. What's weight = 10 for?

Thanks. :+1:

**Comment by nodejh** [comment]
Hi @mrwullah, sorry for the late reply.

1.  In fact, I don't think all tags are in small fonts. I used [jquery.tagcloud.js](https://github.com/addywaddy/jquery.tagcloud.js/) to generate tags with different sizes and colors. But the animation effect is slow, so I give up temporarily.
2. Do you mean the `next` and `previous ` in `config.toml`? It's use to replace the default text in Next page and Previous page buttons, respectively. The default texts are `Older Posts` and `Newer Posts`.
3. `author ` is website's author, it will show in the copyright at the bottom.
4. `menu` is used to add custom navigation menus.
5.  Maybe `weight = 10` which you said is the front matter in [exampleSite](https://github.com/nodejh/hugo-theme-cactus-plus/edit/master/exampleSite/content/posts/creating-a-new-theme.md), it's for nothing :-).

**Comment by mrwullah** [comment]
2. I was thinking it should add `next` and `previous` buttons below every article.

Everything else looks fine for now. :-)
