### ISSUE TITLE
broken line/word wrap

### ISSUE THREAD

**Issue by flypenguin** [nodejh/hugo-theme-mini#87]
when viewing a post the line breaks are ... broken. in the image you see three line endings in a blog post of mine, all three are cut in the middle of a word, which is just plainly wrong ("u", "i" or "frü" are _not_ german words 😆 ). i have identified two possible solutions:

* set `line-break: auto` and `word-break: break-word`
* give users the possibility to add custom CSS (see #85)

<img width="174" alt="grafik" src="https://user-images.githubusercontent.com/5030694/116796845-05b3d580-aae0-11eb-8715-35e35b083900.png">

**Comment by flypenguin** [comment]
nothing? :(

**Comment by nodejh** [comment]
Hi @flypenguin , sorry to reply so late. This PR https://github.com/nodejh/hugo-theme-mini/pull/95 fixed it, and I have merged it :)

**Comment by flypenguin** [comment]
i saw your reply in the PR, thanks! :) 👍
