### ISSUE TITLE
not sure that the mini theme can support table of content in the blog

### ISSUE THREAD

**Issue by brettKK** [nodejh/hugo-theme-mini#88]
I appreciate this hugo-theme, but I'm not sure that this theme can support TOC which I think is very necessary for the writer or reader

**Comment by brettKK** [comment]
I'm not good at html and css

**Comment by nodejh** [comment]
Hi @brettKK , now this theme can support TOC, commit https://github.com/nodejh/hugo-theme-mini/commit/925467c448aac192afd45520cdb95d83bcf67cc1 . 

You can set `showToc: true`  in to enable TOC, this is document: [README#Table Of Content](https://github.com/nodejh/hugo-theme-mini#31-table-of-content)

**Comment by brettKK** [comment]
> Hi @brettKK , now this theme can support TOC, commit [925467c](https://github.com/nodejh/hugo-theme-mini/commit/925467c448aac192afd45520cdb95d83bcf67cc1) .
> 
> You can set `showToc: true` in to enable TOC, this is document: [README#Table Of Content](https://github.com/nodejh/hugo-theme-mini#31-table-of-content)

 i will try it later, thanks for your reply
