### ISSUE TITLE
Code snippet highlight

### ISSUE THREAD

**Issue by BDHU** [nodejh/hugo-theme-mini#90]
Here is the [illustration](https://www.bodunhu.com/blog/posts/start-linux-kernel-hacking/#build-and-install-kernel-modules).

The problem is, the code background highlights only the portion inside the defined width. Once you scroll to the right, the code snippet's background returns to white, Is there any way to fix this issue? Thanks!

**Comment by BDHU** [comment]
For some reason, setting linenos to true fixed the issue. But without it the problem persists

**Comment by nodejh** [comment]
Thanks for your PR https://github.com/nodejh/hugo-theme-mini/pull/91 to solve this problem, I have merged it.
