### ISSUE TITLE
请问“关于”页面如何禁用disqus评论

### ISSUE THREAD

**Issue by yuxingwei** [nodejh/hugo-theme-mini#97]
场景：
1. 尝试在_index.md文本头上设置comments: false或者使用comments = false使禁用评论功能生效

结果：
1. 并未达到预期

备注：
1. Demo Site中的关于页面评论同样是开启，nodejh.com关于页中是关闭的。请问您如何能将其在关于页面中禁用评论呢

**Comment by BDHU** [comment]
注释掉 [https://github.com/nodejh/hugo-theme-mini/blob/8628c19610c7420ea776f7871d40902cf5382c25/layouts/_default/single.html#L40](https://github.com/nodejh/hugo-theme-mini/blob/8628c19610c7420ea776f7871d40902cf5382c25/layouts/_default/single.html#L40).

**Comment by yuxingwei** [comment]
> 注释掉
> 
> https://github.com/nodejh/hugo-theme-mini/blob/8628c19610c7420ea776f7871d40902cf5382c25/layouts/_default/single.html#L40
> 
> .

很高兴可以收到你的回复。你说的是指包括文章页面的评论也关闭。这种方式可以直接在config.yaml中进行全局配置完成。我所提到的场景是这样的。你可以参考nodejh.com中，内容页中评论功能是开启的，关于页面的评论功能是关闭的。

备注：我的关于页面md文件格式参照exampleSite中about目录下的_index.md来写的。尝试了前面提到的两种配置方式均未生效

**Comment by BDHU** [comment]
Not sure if this works:
[https://github.com/nodejh/hugo-theme-mini/blob/8628c19610c7420ea776f7871d40902cf5382c25/layouts/section/about.html#L7](https://github.com/nodejh/hugo-theme-mini/blob/8628c19610c7420ea776f7871d40902cf5382c25/layouts/section/about.html#L7)

**Comment by yuxingwei** [comment]
> Not sure if this works:
> https://github.com/nodejh/hugo-theme-mini/blob/8628c19610c7420ea776f7871d40902cf5382c25/layouts/section/about.html#L7

谢谢，它生效了
